-- ====================================================================================
-- MULTI-TENANT SAAS HOSPITAL MANAGEMENT SYSTEM (HMS) - FULL DATABASE SCHEMA SCRIPT
-- Supports Phase 1 (Foundation), Phase 2 (Core), Phase 3 (Clinical), Phase 4 (Revenue), Phase 5 (SaaS)
-- ====================================================================================

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'HMS')
BEGIN
    CREATE DATABASE HMS;
END
GO

USE HMS;
GO

-- ==========================================
-- PHASE 1: FOUNDATION & MULTI-TENANCY
-- ==========================================

-- 1. Tenants (Hospital Organizations)
CREATE TABLE Tenants (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantCode NVARCHAR(50) NOT NULL UNIQUE,
    Name NVARCHAR(150) NOT NULL,
    LegalName NVARCHAR(200) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(20) NOT NULL,
    TimeZone NVARCHAR(50) DEFAULT 'UTC' NOT NULL,
    Currency NVARCHAR(10) DEFAULT 'USD' NOT NULL,
    Country NVARCHAR(100) DEFAULT 'USA' NOT NULL,
    Status NVARCHAR(30) DEFAULT 'Active' NOT NULL,
    Subdomain NVARCHAR(100) NULL,
    CustomDomain NVARCHAR(150) NULL,
    DedicatedConnectionString NVARCHAR(500) NULL,
    IsolationStrategy INT DEFAULT 0 NOT NULL, -- 0: SharedDatabase, 1: DedicatedDatabase
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL,
    IsDeleted BIT DEFAULT 0 NOT NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy NVARCHAR(100) NULL
);

-- 2. Branches
CREATE TABLE Branches (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchCode NVARCHAR(50) NOT NULL,
    Name NVARCHAR(150) NOT NULL,
    Address NVARCHAR(250) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    State NVARCHAR(100) NOT NULL,
    Country NVARCHAR(100) NOT NULL,
    PinCode NVARCHAR(20) NOT NULL,
    Phone NVARCHAR(20) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Status NVARCHAR(30) DEFAULT 'Active' NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL,
    IsDeleted BIT DEFAULT 0 NOT NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy NVARCHAR(100) NULL
);

-- 3. TenantSettings
CREATE TABLE TenantSettings (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    DateFormat NVARCHAR(30) DEFAULT 'yyyy-MM-dd' NOT NULL,
    TimeZone NVARCHAR(50) DEFAULT 'UTC' NOT NULL,
    Currency NVARCHAR(10) DEFAULT 'USD' NOT NULL,
    Language NVARCHAR(10) DEFAULT 'en' NOT NULL,
    TaxNumber NVARCHAR(50) NULL,
    LogoUrl NVARCHAR(500) NULL,
    InvoicePrefix NVARCHAR(20) DEFAULT 'INV-' NOT NULL,
    PatientPrefix NVARCHAR(20) DEFAULT 'PAT-' NOT NULL,
    BillingSettingsJson NVARCHAR(MAX) NULL,
    NotificationSettingsJson NVARCHAR(MAX) NULL,
    SecuritySettingsJson NVARCHAR(MAX) NULL,
    FeatureSettingsJson NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL
);

-- 4. Departments
CREATE TABLE Departments (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    Name NVARCHAR(100) NOT NULL,
    Code NVARCHAR(30) NOT NULL,
    Description NVARCHAR(250) NULL,
    IsActive BIT DEFAULT 1 NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL,
    IsDeleted BIT DEFAULT 0 NOT NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy NVARCHAR(100) NULL
);

-- 5. Users
CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    DepartmentId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Departments(Id),
    Email NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(20) NOT NULL,
    PasswordHash NVARCHAR(256) NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Role NVARCHAR(50) DEFAULT 'User' NOT NULL,
    Status NVARCHAR(30) DEFAULT 'Active' NOT NULL,
    LastLoginAt DATETIME2 NULL,
    EmailVerified BIT DEFAULT 0 NOT NULL,
    AccessFailedCount INT DEFAULT 0 NOT NULL,
    LockoutEnd DATETIME2 NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL,
    IsDeleted BIT DEFAULT 0 NOT NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy NVARCHAR(100) NULL
);

-- 6. Roles & Permissions (RBAC)
CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    Name NVARCHAR(100) NOT NULL,
    Code NVARCHAR(50) NOT NULL,
    IsSystemRole BIT DEFAULT 0 NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL
);

CREATE TABLE Permissions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Module NVARCHAR(50) NOT NULL,
    Code NVARCHAR(100) NOT NULL UNIQUE,
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE UserRoles (
    UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(Id),
    RoleId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Roles(Id),
    PRIMARY KEY (UserId, RoleId)
);

CREATE TABLE RolePermissions (
    RoleId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Roles(Id),
    PermissionId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Permissions(Id),
    PRIMARY KEY (RoleId, PermissionId)
);

CREATE TABLE RefreshTokens (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(Id),
    Token NVARCHAR(500) NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    IsRevoked BIT DEFAULT 0 NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL
);

-- 7. AuditLogs
CREATE TABLE AuditLogs (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL,
    BranchId UNIQUEIDENTIFIER NULL,
    UserId UNIQUEIDENTIFIER NULL,
    Action NVARCHAR(100) NOT NULL,
    Module NVARCHAR(100) NOT NULL,
    EntityName NVARCHAR(100) NOT NULL,
    EntityId NVARCHAR(100) NOT NULL,
    OldValues NVARCHAR(MAX) NULL,
    NewValues NVARCHAR(MAX) NULL,
    IPAddress NVARCHAR(50) NULL,
    UserAgent NVARCHAR(500) NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL
);


-- ==========================================
-- PHASE 2: CORE HOSPITAL OPERATIONS
-- ==========================================

-- 8. Patients
CREATE TABLE Patients (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    MRN NVARCHAR(50) NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Gender NVARCHAR(20) NOT NULL,
    DOB DATE NOT NULL,
    BloodGroup NVARCHAR(10) NULL,
    Phone NVARCHAR(20) NOT NULL,
    Email NVARCHAR(100) NULL,
    Status NVARCHAR(30) DEFAULT 'Active' NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL,
    IsDeleted BIT DEFAULT 0 NOT NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy NVARCHAR(100) NULL
);

CREATE TABLE PatientAddresses (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    AddressType NVARCHAR(30) DEFAULT 'Home' NOT NULL,
    AddressLine1 NVARCHAR(200) NOT NULL,
    AddressLine2 NVARCHAR(200) NULL,
    City NVARCHAR(100) NOT NULL,
    State NVARCHAR(100) NOT NULL,
    Country NVARCHAR(100) NOT NULL,
    PinCode NVARCHAR(20) NOT NULL
);

CREATE TABLE PatientContacts (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    ContactName NVARCHAR(150) NOT NULL,
    Relationship NVARCHAR(50) NOT NULL,
    Phone NVARCHAR(20) NOT NULL,
    Email NVARCHAR(100) NULL,
    IsEmergencyContact BIT DEFAULT 0 NOT NULL
);

CREATE TABLE PatientDocuments (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL,
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    DocumentType NVARCHAR(50) NOT NULL,
    DocumentName NVARCHAR(150) NOT NULL,
    FileUrl NVARCHAR(500) NOT NULL,
    UploadedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL
);

-- 9. Doctors
CREATE TABLE Doctors (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    UserId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Users(Id),
    DoctorNo NVARCHAR(50) NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Specialization NVARCHAR(100) NOT NULL,
    Qualification NVARCHAR(100) NOT NULL,
    RegistrationNumber NVARCHAR(50) NOT NULL,
    ConsultationFee DECIMAL(18,2) DEFAULT 0 NOT NULL,
    Phone NVARCHAR(20) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Status NVARCHAR(30) DEFAULT 'Active' NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL,
    IsDeleted BIT DEFAULT 0 NOT NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy NVARCHAR(100) NULL
);

CREATE TABLE DoctorDepartments (
    DoctorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Doctors(Id),
    DepartmentId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Departments(Id),
    PRIMARY KEY (DoctorId, DepartmentId)
);

CREATE TABLE DoctorSchedules (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    DoctorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Doctors(Id),
    DayOfWeek INT NOT NULL, -- 0: Sunday, 1: Monday, etc.
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    SlotDurationMinutes INT DEFAULT 15 NOT NULL,
    MaxPatients INT DEFAULT 20 NOT NULL,
    IsAvailable BIT DEFAULT 1 NOT NULL
);

-- 10. Hospital Services Catalog
CREATE TABLE HospitalServices (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    DepartmentId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Departments(Id),
    ServiceCode NVARCHAR(50) NOT NULL,
    ServiceName NVARCHAR(150) NOT NULL,
    Description NVARCHAR(500) NULL,
    Price DECIMAL(18,2) NOT NULL,
    IsActive BIT DEFAULT 1 NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL
);

-- 11. Appointments
CREATE TABLE Appointments (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    AppointmentNo NVARCHAR(50) NOT NULL,
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    DoctorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Doctors(Id),
    DepartmentId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Departments(Id),
    ServiceId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES HospitalServices(Id),
    AppointmentDate DATE NOT NULL,
    SlotStartTime TIME NOT NULL,
    SlotEndTime TIME NOT NULL,
    TokenNumber INT NOT NULL,
    Status NVARCHAR(30) DEFAULT 'Scheduled' NOT NULL,
    Reason NVARCHAR(500) NULL,
    ConsultationFee DECIMAL(18,2) DEFAULT 0 NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL,
    IsDeleted BIT DEFAULT 0 NOT NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy NVARCHAR(100) NULL
);


-- ==========================================
-- PHASE 3: CLINICAL OPERATIONS (OPD, IPD, EMR)
-- ==========================================

-- 12. Consultations & Diagnoses
CREATE TABLE Consultations (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    AppointmentId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Appointments(Id),
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    DoctorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Doctors(Id),
    ConsultationDate DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    ChiefComplaints NVARCHAR(MAX) NULL,
    ClinicalNotes NVARCHAR(MAX) NULL,
    Advice NVARCHAR(MAX) NULL,
    FollowUpDate DATE NULL,
    Status NVARCHAR(30) DEFAULT 'Completed' NOT NULL
);

CREATE TABLE Diagnoses (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ConsultationId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Consultations(Id),
    ICD10Code NVARCHAR(30) NULL,
    DiagnosisName NVARCHAR(250) NOT NULL,
    Type NVARCHAR(30) DEFAULT 'Primary' NOT NULL -- Primary, Secondary
);

-- 13. Prescriptions
CREATE TABLE Prescriptions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    ConsultationId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Consultations(Id),
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    DoctorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Doctors(Id),
    PrescriptionDate DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    Instructions NVARCHAR(MAX) NULL
);

CREATE TABLE PrescriptionItems (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PrescriptionId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Prescriptions(Id),
    MedicineName NVARCHAR(150) NOT NULL,
    Dosage NVARCHAR(50) NOT NULL, -- e.g. "1-0-1"
    Frequency NVARCHAR(50) NOT NULL, -- "Twice Daily"
    DurationDays INT NOT NULL,
    Instructions NVARCHAR(250) NULL
);

-- 14. Wards, Rooms, Beds & IPD Admissions
CREATE TABLE Wards (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    WardName NVARCHAR(100) NOT NULL,
    WardType NVARCHAR(50) NOT NULL, -- General, ICU, Private, SemiPrivate
    Floor NVARCHAR(30) NOT NULL
);

CREATE TABLE Rooms (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    WardId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Wards(Id),
    RoomNumber NVARCHAR(30) NOT NULL,
    RoomType NVARCHAR(50) NOT NULL
);

CREATE TABLE Beds (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    RoomId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Rooms(Id),
    BedNumber NVARCHAR(30) NOT NULL,
    DailyCharge DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(30) DEFAULT 'Available' NOT NULL -- Available, Occupied, Maintenance
);

CREATE TABLE Admissions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    AdmissionNo NVARCHAR(50) NOT NULL,
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    AttendingDoctorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Doctors(Id),
    BedId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Beds(Id),
    AdmissionDate DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    DischargeDate DATETIME2 NULL,
    Status NVARCHAR(30) DEFAULT 'Admitted' NOT NULL, -- Admitted, Discharged
    ReasonForAdmission NVARCHAR(MAX) NULL
);

CREATE TABLE Discharges (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    AdmissionId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Admissions(Id),
    DischargeDate DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    DischargeSummary NVARCHAR(MAX) NOT NULL,
    ConditionAtDischarge NVARCHAR(100) NOT NULL
);

-- 15. Nursing Notes & Vitals
CREATE TABLE Vitals (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    AdmissionId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Admissions(Id),
    RecordedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    BloodPressure NVARCHAR(20) NULL,
    PulseRate INT NULL,
    TemperatureDecimal DECIMAL(5,2) NULL,
    OxygenSaturation INT NULL,
    RespiratoryRate INT NULL
);


-- ==========================================
-- PHASE 4: REVENUE, ANCILLARY & INVENTORY
-- ==========================================

-- 16. Billing, Invoices & Payments
CREATE TABLE Invoices (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    BranchId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Branches(Id),
    InvoiceNumber NVARCHAR(50) NOT NULL,
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    SubTotal DECIMAL(18,2) NOT NULL,
    DiscountAmount DECIMAL(18,2) DEFAULT 0 NOT NULL,
    TaxAmount DECIMAL(18,2) DEFAULT 0 NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    PaidAmount DECIMAL(18,2) DEFAULT 0 NOT NULL,
    Status NVARCHAR(30) DEFAULT 'Unpaid' NOT NULL, -- Unpaid, PartiallyPaid, Paid
    InvoiceDate DATETIME2 DEFAULT GETUTCDATE() NOT NULL
);

CREATE TABLE InvoiceItems (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    InvoiceId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Invoices(Id),
    ItemDescription NVARCHAR(250) NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    Quantity INT DEFAULT 1 NOT NULL,
    TotalPrice DECIMAL(18,2) NOT NULL
);

CREATE TABLE Payments (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    InvoiceId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Invoices(Id),
    PaymentNumber NVARCHAR(50) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentMethod NVARCHAR(50) NOT NULL, -- Cash, Card, UPI, Insurance
    PaymentDate DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    TransactionRef NVARCHAR(100) NULL
);

-- 17. Pharmacy & Medicines
CREATE TABLE Medicines (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    MedicineCode NVARCHAR(50) NOT NULL,
    Name NVARCHAR(150) NOT NULL,
    GenericName NVARCHAR(150) NULL,
    Category NVARCHAR(100) NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    StockQuantity INT DEFAULT 0 NOT NULL,
    ExpiryDate DATE NOT NULL
);

-- 18. Laboratory & Radiology
CREATE TABLE LabOrders (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    PatientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Patients(Id),
    DoctorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Doctors(Id),
    TestName NVARCHAR(150) NOT NULL,
    Status NVARCHAR(30) DEFAULT 'Ordered' NOT NULL, -- Ordered, SampleCollected, Completed
    ResultSummary NVARCHAR(MAX) NULL,
    OrderDate DATETIME2 DEFAULT GETUTCDATE() NOT NULL
);


-- ==========================================
-- PHASE 5: SAAS SUBSCRIPTION PLATFORM
-- ==========================================

-- 19. SaaS Plans & Features
CREATE TABLE Plans (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL, -- Starter, Professional, Enterprise
    Code NVARCHAR(50) NOT NULL UNIQUE,
    Description NVARCHAR(500) NOT NULL,
    PriceMonthly DECIMAL(18,2) NOT NULL,
    PriceYearly DECIMAL(18,2) NOT NULL,
    TrialDays INT DEFAULT 14 NOT NULL,
    Status NVARCHAR(30) DEFAULT 'Active' NOT NULL
);

CREATE TABLE PlanFeatures (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PlanId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Plans(Id),
    FeatureCode NVARCHAR(100) NOT NULL, -- MaxBranches, MaxUsers, MaxDoctors, MaxPatients, Pharmacy, Lab, Radiology, APIAccess
    LimitType NVARCHAR(30) DEFAULT 'Numeric' NOT NULL, -- Numeric, Boolean, Unlimited
    LimitValue NVARCHAR(50) NOT NULL
);

-- 20. Tenant Subscriptions
CREATE TABLE TenantSubscriptions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tenants(Id),
    PlanId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Plans(Id),
    Status NVARCHAR(30) DEFAULT 'Active' NOT NULL, -- Trialing, Active, PastDue, Suspended, Cancelled
    StartDate DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    EndDate DATETIME2 NOT NULL,
    TrialEndDate DATETIME2 NULL,
    NextBillingDate DATETIME2 NULL,
    AutoRenew BIT DEFAULT 1 NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy NVARCHAR(100) NULL
);

CREATE TABLE SubscriptionItems (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SubscriptionId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TenantSubscriptions(Id),
    FeatureCode NVARCHAR(100) NOT NULL,
    Quantity INT DEFAULT 1 NOT NULL,
    Price DECIMAL(18,2) DEFAULT 0 NOT NULL
);
GO

